// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(document).ready(function($) {
    var $body, $menu, $parallaxes, doParallaxes;
    $body = $('body');
    $.touchEnabled = typeof ontouchstart !== 'undefined';
    $menu = $('body > header nav');
    $menu.on('click', function(e) {
      $body.toggleClass('menuOpen');
      if ($(e.target).prop('tagName').toLowerCase() !== 'a') {
        e.preventDefault();
        return false;
      }
    });
    $('html').click(function() {
      return $body.removeClass('menuOpen');
    });
    $parallaxes = $('section[role=parallax]');
    if ($parallaxes.length > 0) {
      if ($.touchEnabled) {
        return $parallaxes.css({
          backgroundPosition: '50% 50%'
        });
      } else {
        doParallaxes = function() {
          var scrolled;
          scrolled = $(window).scrollTop();
          return $parallaxes.each(function() {
            var $this, bgOffsetPerc, excess, height, offset, passed;
            $this = $(this);
            height = 480;
            excess = 240;
            offset = $this.offset().top;
            passed = scrolled - offset;
            if (passed < 0) {
              bgOffsetPerc = 100;
            } else if (passed > height) {
              bgOffsetPerc = 0;
            } else {
              bgOffsetPerc = 100 - (passed / height * 100);
            }
            return $this.css({
              backgroundPosition: "50% " + bgOffsetPerc + "%"
            });
          });
        };
        $(window).resize(doParallaxes);
        return $(window).scroll(doParallaxes);
      }
    }
  });

}).call(this);
